{
 "title": "ydb-go-sdk-v2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(driver_dial_calls{success=\"true\"},address)"
    }
   },
   {
    "name": "metrics_with_address",
    "label": "Driver Metrics",
    "query": "driver_dial, driver_discovery,driver_pessimize,driver_conn_get,driver_operation,driver_stream_operation"
   },
   {
    "name": "metrics_with_nodeid",
    "label": "Table Metrics",
    "query": "table_session_new,table_session_delete,table_session_keep_alive,table_session_prepare,table_session_execute,table_session_stream_execute,table_session_stream_read,table_session_tx_begin,table_session_tx_commit,table_session_tx_rollback"
   }
  ]
 },
 "panels": [
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_calls{success=~\"(true|false)\"}[$__interval])) by (method,success)",
     "legendFormat": "{{method}} -> {{success}}"
    }
   ]
  },
  {
   "title": "Latency (Data Query)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_latency_bucket{method=\"data\"}[$__interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(app_latency_bucket{method=\"data\"}[$__interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_latency_bucket{method=\"data\"}[$__interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_latency_bucket{method=\"data\"}[$__interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(app_latency_bucket{method=\"data\"}[$__interval])) by (le))",
     "legendFormat": "p25"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(app_latency_bucket{method=\"data\"}[$__interval])) by (le))",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Uptimes",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uptime_value", "legendFormat": "value" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "goroutines_value", "legendFormat": "value" }
   ]
  },
  {
   "title": "Errors [by type]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_errors{}[$__interval])) by (method,error,errCode)",
     "legendFormat": "{{method}} -> {{error}} [{{errCode}}]"
    }
   ]
  },
  {
   "title": "Latency (Scan Query)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_latency_bucket{method=\"scan\"}[$__interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(app_latency_bucket{method=\"scan\"}[$__interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_latency_bucket{method=\"scan\"}[$__interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_latency_bucket{method=\"scan\"}[$__interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(app_latency_bucket{method=\"scan\"}[$__interval])) by (le))",
     "legendFormat": "p25"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(app_latency_bucket{method=\"scan\"}[$__interval])) by (le))",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_value", "legendFormat": "value" }
   ]
  },
  {
   "title": "$metrics_with_address",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "metrics_with_address",
   "collapsed": true,
   "panels": [
    {
     "title": "Calls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(${metrics_with_address}_calls{address=~\"$endpoint\",success=~\"(true|false)\"}[$__interval])) by (address)",
       "legendFormat": "{{address}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(${metrics_with_address}_latency_bucket[$__interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(${metrics_with_address}_latency_bucket[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(${metrics_with_address}_latency_bucket[$__interval])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(${metrics_with_address}_latency_bucket[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.25, sum(rate(${metrics_with_address}_latency_bucket[$__interval])) by (le))",
       "legendFormat": "p25"
      },
      {
       "expr": "histogram_quantile(0.1, sum(rate(${metrics_with_address}_latency_bucket[$__interval])) by (le))",
       "legendFormat": "p10"
      }
     ]
    },
    {
     "title": "Errors [by endpoint]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(${metrics_with_address}_errors{address=~\"$endpoint\"}[$__interval])) by (address)",
       "legendFormat": "{{address}}"
      }
     ]
    },
    {
     "title": "Calls [by method if exists]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(${metrics_with_address}_calls{address=~\"$endpoint\",success=~\"(true|false)\"}[$__interval])) by (method,success))",
       "legendFormat": "{{method}}, success={{success}}"
      }
     ]
    },
    {
     "title": "Value [if exists]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "${metrics_with_address}_value", "legendFormat": "value" }
     ]
    },
    {
     "title": "Errors [by type]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(${metrics_with_address}_errors{address=~\"$endpoint\"}[$__interval])) by (error,errCode)",
       "legendFormat": "{{error}} [{{errCode}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "$metrics_with_nodeid",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "metrics_with_nodeid",
   "collapsed": true,
   "panels": [
    {
     "title": "Calls [rps]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(${metrics_with_nodeid}_calls{nodeID!=\"\",success=~\"(true|false)\"}[$__interval])) by (nodeID))",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(${metrics_with_nodeid}_latency_bucket{nodeID!=\"\",success=~\"(true|false)\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(${metrics_with_nodeid}_latency_bucket{nodeID!=\"\",success=~\"(true|false)\"}[$__interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(${metrics_with_nodeid}_latency_bucket{nodeID!=\"\",success=~\"(true|false)\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(${metrics_with_nodeid}_latency_bucket{nodeID!=\"\",success=~\"(true|false)\"}[$__interval])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(${metrics_with_nodeid}_latency_bucket{nodeID!=\"\",success=~\"(true|false)\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.25, sum(rate(${metrics_with_nodeid}_latency_bucket{nodeID!=\"\",success=~\"(true|false)\"}[$__interval])) by (le))",
       "legendFormat": "p25"
      },
      {
       "expr": "histogram_quantile(0.1, sum(rate(${metrics_with_nodeid}_latency_bucket{nodeID!=\"\",success=~\"(true|false)\"}[$__interval])) by (le))",
       "legendFormat": "p10"
      }
     ]
    },
    {
     "title": "Errors [by endpoint]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(${metrics_with_nodeid}_errors[$__interval])) by (nodeID)",
       "legendFormat": "{{address}}"
      }
     ]
    },
    {
     "title": "Value [if exists]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(${metrics_with_nodeid}_value{nodeID!=\"\"}) by (nodeID))"
      }
     ]
    },
    {
     "title": "Errors [by type]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(${metrics_with_nodeid}_errors[$__interval])) by (error,errCode)",
       "legendFormat": "{{error}} [{{errCode}}]"
      }
     ]
    }
   ]
  }
 ]
}