// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ydb_import.proto

package Ydb_Import

import (
	Ydb_Operations "github.com/yandex-cloud/ydb-go-sdk/v2/api/protos/Ydb_Operations"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImportProgress_Progress int32

const (
	ImportProgress_PROGRESS_UNSPECIFIED   ImportProgress_Progress = 0
	ImportProgress_PROGRESS_PREPARING     ImportProgress_Progress = 1
	ImportProgress_PROGRESS_TRANSFER_DATA ImportProgress_Progress = 2
	ImportProgress_PROGRESS_BUILD_INDEXES ImportProgress_Progress = 3
	ImportProgress_PROGRESS_DONE          ImportProgress_Progress = 4
	ImportProgress_PROGRESS_CANCELLATION  ImportProgress_Progress = 5
	ImportProgress_PROGRESS_CANCELLED     ImportProgress_Progress = 6
)

var ImportProgress_Progress_name = map[int32]string{
	0: "PROGRESS_UNSPECIFIED",
	1: "PROGRESS_PREPARING",
	2: "PROGRESS_TRANSFER_DATA",
	3: "PROGRESS_BUILD_INDEXES",
	4: "PROGRESS_DONE",
	5: "PROGRESS_CANCELLATION",
	6: "PROGRESS_CANCELLED",
}

var ImportProgress_Progress_value = map[string]int32{
	"PROGRESS_UNSPECIFIED":   0,
	"PROGRESS_PREPARING":     1,
	"PROGRESS_TRANSFER_DATA": 2,
	"PROGRESS_BUILD_INDEXES": 3,
	"PROGRESS_DONE":          4,
	"PROGRESS_CANCELLATION":  5,
	"PROGRESS_CANCELLED":     6,
}

func (x ImportProgress_Progress) String() string {
	return proto.EnumName(ImportProgress_Progress_name, int32(x))
}

func (ImportProgress_Progress) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{0, 0}
}

type ImportFromS3Settings_Scheme int32

const (
	ImportFromS3Settings_UNSPECIFIED ImportFromS3Settings_Scheme = 0
	ImportFromS3Settings_HTTP        ImportFromS3Settings_Scheme = 1
	ImportFromS3Settings_HTTPS       ImportFromS3Settings_Scheme = 2
)

var ImportFromS3Settings_Scheme_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "HTTP",
	2: "HTTPS",
}

var ImportFromS3Settings_Scheme_value = map[string]int32{
	"UNSPECIFIED": 0,
	"HTTP":        1,
	"HTTPS":       2,
}

func (x ImportFromS3Settings_Scheme) String() string {
	return proto.EnumName(ImportFromS3Settings_Scheme_name, int32(x))
}

func (ImportFromS3Settings_Scheme) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{2, 0}
}

/// Common
type ImportProgress struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportProgress) Reset()         { *m = ImportProgress{} }
func (m *ImportProgress) String() string { return proto.CompactTextString(m) }
func (*ImportProgress) ProtoMessage()    {}
func (*ImportProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{0}
}

func (m *ImportProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportProgress.Unmarshal(m, b)
}
func (m *ImportProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportProgress.Marshal(b, m, deterministic)
}
func (m *ImportProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportProgress.Merge(m, src)
}
func (m *ImportProgress) XXX_Size() int {
	return xxx_messageInfo_ImportProgress.Size(m)
}
func (m *ImportProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportProgress.DiscardUnknown(m)
}

var xxx_messageInfo_ImportProgress proto.InternalMessageInfo

type ImportItemProgress struct {
	PartsTotal           uint32                 `protobuf:"varint,1,opt,name=parts_total,json=partsTotal,proto3" json:"parts_total,omitempty"`
	PartsCompleted       uint32                 `protobuf:"varint,2,opt,name=parts_completed,json=partsCompleted,proto3" json:"parts_completed,omitempty"`
	StartTime            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ImportItemProgress) Reset()         { *m = ImportItemProgress{} }
func (m *ImportItemProgress) String() string { return proto.CompactTextString(m) }
func (*ImportItemProgress) ProtoMessage()    {}
func (*ImportItemProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{1}
}

func (m *ImportItemProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportItemProgress.Unmarshal(m, b)
}
func (m *ImportItemProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportItemProgress.Marshal(b, m, deterministic)
}
func (m *ImportItemProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportItemProgress.Merge(m, src)
}
func (m *ImportItemProgress) XXX_Size() int {
	return xxx_messageInfo_ImportItemProgress.Size(m)
}
func (m *ImportItemProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportItemProgress.DiscardUnknown(m)
}

var xxx_messageInfo_ImportItemProgress proto.InternalMessageInfo

func (m *ImportItemProgress) GetPartsTotal() uint32 {
	if m != nil {
		return m.PartsTotal
	}
	return 0
}

func (m *ImportItemProgress) GetPartsCompleted() uint32 {
	if m != nil {
		return m.PartsCompleted
	}
	return 0
}

func (m *ImportItemProgress) GetStartTime() *timestamppb.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ImportItemProgress) GetEndTime() *timestamppb.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

/// S3
type ImportFromS3Settings struct {
	Endpoint             string                       `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Scheme               ImportFromS3Settings_Scheme  `protobuf:"varint,2,opt,name=scheme,proto3,enum=Ydb.Import.ImportFromS3Settings_Scheme" json:"scheme,omitempty"`
	Bucket               string                       `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessKey            string                       `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey            string                       `protobuf:"bytes,5,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Items                []*ImportFromS3Settings_Item `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	Description          string                       `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	NumberOfRetries      uint32                       `protobuf:"varint,8,opt,name=number_of_retries,json=numberOfRetries,proto3" json:"number_of_retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ImportFromS3Settings) Reset()         { *m = ImportFromS3Settings{} }
func (m *ImportFromS3Settings) String() string { return proto.CompactTextString(m) }
func (*ImportFromS3Settings) ProtoMessage()    {}
func (*ImportFromS3Settings) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{2}
}

func (m *ImportFromS3Settings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportFromS3Settings.Unmarshal(m, b)
}
func (m *ImportFromS3Settings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportFromS3Settings.Marshal(b, m, deterministic)
}
func (m *ImportFromS3Settings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportFromS3Settings.Merge(m, src)
}
func (m *ImportFromS3Settings) XXX_Size() int {
	return xxx_messageInfo_ImportFromS3Settings.Size(m)
}
func (m *ImportFromS3Settings) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportFromS3Settings.DiscardUnknown(m)
}

var xxx_messageInfo_ImportFromS3Settings proto.InternalMessageInfo

func (m *ImportFromS3Settings) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *ImportFromS3Settings) GetScheme() ImportFromS3Settings_Scheme {
	if m != nil {
		return m.Scheme
	}
	return ImportFromS3Settings_UNSPECIFIED
}

func (m *ImportFromS3Settings) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ImportFromS3Settings) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *ImportFromS3Settings) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *ImportFromS3Settings) GetItems() []*ImportFromS3Settings_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ImportFromS3Settings) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ImportFromS3Settings) GetNumberOfRetries() uint32 {
	if m != nil {
		return m.NumberOfRetries
	}
	return 0
}

type ImportFromS3Settings_Item struct {
	// YDB tables in S3 are stored in one or more objects (see ydb_export.proto).
	//The object name begins with 'source_prefix'.
	//This prefix is followed by:
	// '/data_PartNumber', where 'PartNumber' represents the index of the part, starting at zero;
	// '/scheme.pb' - object with information about scheme, indexes, etc.
	SourcePrefix string `protobuf:"bytes,1,opt,name=source_prefix,json=sourcePrefix,proto3" json:"source_prefix,omitempty"`
	// Database path to a table to import to.
	DestinationPath      string   `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportFromS3Settings_Item) Reset()         { *m = ImportFromS3Settings_Item{} }
func (m *ImportFromS3Settings_Item) String() string { return proto.CompactTextString(m) }
func (*ImportFromS3Settings_Item) ProtoMessage()    {}
func (*ImportFromS3Settings_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{2, 0}
}

func (m *ImportFromS3Settings_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportFromS3Settings_Item.Unmarshal(m, b)
}
func (m *ImportFromS3Settings_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportFromS3Settings_Item.Marshal(b, m, deterministic)
}
func (m *ImportFromS3Settings_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportFromS3Settings_Item.Merge(m, src)
}
func (m *ImportFromS3Settings_Item) XXX_Size() int {
	return xxx_messageInfo_ImportFromS3Settings_Item.Size(m)
}
func (m *ImportFromS3Settings_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportFromS3Settings_Item.DiscardUnknown(m)
}

var xxx_messageInfo_ImportFromS3Settings_Item proto.InternalMessageInfo

func (m *ImportFromS3Settings_Item) GetSourcePrefix() string {
	if m != nil {
		return m.SourcePrefix
	}
	return ""
}

func (m *ImportFromS3Settings_Item) GetDestinationPath() string {
	if m != nil {
		return m.DestinationPath
	}
	return ""
}

type ImportFromS3Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportFromS3Result) Reset()         { *m = ImportFromS3Result{} }
func (m *ImportFromS3Result) String() string { return proto.CompactTextString(m) }
func (*ImportFromS3Result) ProtoMessage()    {}
func (*ImportFromS3Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{3}
}

func (m *ImportFromS3Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportFromS3Result.Unmarshal(m, b)
}
func (m *ImportFromS3Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportFromS3Result.Marshal(b, m, deterministic)
}
func (m *ImportFromS3Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportFromS3Result.Merge(m, src)
}
func (m *ImportFromS3Result) XXX_Size() int {
	return xxx_messageInfo_ImportFromS3Result.Size(m)
}
func (m *ImportFromS3Result) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportFromS3Result.DiscardUnknown(m)
}

var xxx_messageInfo_ImportFromS3Result proto.InternalMessageInfo

type ImportFromS3Metadata struct {
	Settings             *ImportFromS3Settings   `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	Progress             ImportProgress_Progress `protobuf:"varint,2,opt,name=progress,proto3,enum=Ydb.Import.ImportProgress_Progress" json:"progress,omitempty"`
	ItemsProgress        []*ImportItemProgress   `protobuf:"bytes,3,rep,name=items_progress,json=itemsProgress,proto3" json:"items_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ImportFromS3Metadata) Reset()         { *m = ImportFromS3Metadata{} }
func (m *ImportFromS3Metadata) String() string { return proto.CompactTextString(m) }
func (*ImportFromS3Metadata) ProtoMessage()    {}
func (*ImportFromS3Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{4}
}

func (m *ImportFromS3Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportFromS3Metadata.Unmarshal(m, b)
}
func (m *ImportFromS3Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportFromS3Metadata.Marshal(b, m, deterministic)
}
func (m *ImportFromS3Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportFromS3Metadata.Merge(m, src)
}
func (m *ImportFromS3Metadata) XXX_Size() int {
	return xxx_messageInfo_ImportFromS3Metadata.Size(m)
}
func (m *ImportFromS3Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportFromS3Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_ImportFromS3Metadata proto.InternalMessageInfo

func (m *ImportFromS3Metadata) GetSettings() *ImportFromS3Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *ImportFromS3Metadata) GetProgress() ImportProgress_Progress {
	if m != nil {
		return m.Progress
	}
	return ImportProgress_PROGRESS_UNSPECIFIED
}

func (m *ImportFromS3Metadata) GetItemsProgress() []*ImportItemProgress {
	if m != nil {
		return m.ItemsProgress
	}
	return nil
}

type ImportFromS3Request struct {
	OperationParams      *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3" json:"operation_params,omitempty"`
	Settings             *ImportFromS3Settings           `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ImportFromS3Request) Reset()         { *m = ImportFromS3Request{} }
func (m *ImportFromS3Request) String() string { return proto.CompactTextString(m) }
func (*ImportFromS3Request) ProtoMessage()    {}
func (*ImportFromS3Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{5}
}

func (m *ImportFromS3Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportFromS3Request.Unmarshal(m, b)
}
func (m *ImportFromS3Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportFromS3Request.Marshal(b, m, deterministic)
}
func (m *ImportFromS3Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportFromS3Request.Merge(m, src)
}
func (m *ImportFromS3Request) XXX_Size() int {
	return xxx_messageInfo_ImportFromS3Request.Size(m)
}
func (m *ImportFromS3Request) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportFromS3Request.DiscardUnknown(m)
}

var xxx_messageInfo_ImportFromS3Request proto.InternalMessageInfo

func (m *ImportFromS3Request) GetOperationParams() *Ydb_Operations.OperationParams {
	if m != nil {
		return m.OperationParams
	}
	return nil
}

func (m *ImportFromS3Request) GetSettings() *ImportFromS3Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type ImportFromS3Response struct {
	// operation.result = ImportFromS3Result
	// operation.metadata = ImportFromS3Metadata
	Operation            *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ImportFromS3Response) Reset()         { *m = ImportFromS3Response{} }
func (m *ImportFromS3Response) String() string { return proto.CompactTextString(m) }
func (*ImportFromS3Response) ProtoMessage()    {}
func (*ImportFromS3Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{6}
}

func (m *ImportFromS3Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportFromS3Response.Unmarshal(m, b)
}
func (m *ImportFromS3Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportFromS3Response.Marshal(b, m, deterministic)
}
func (m *ImportFromS3Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportFromS3Response.Merge(m, src)
}
func (m *ImportFromS3Response) XXX_Size() int {
	return xxx_messageInfo_ImportFromS3Response.Size(m)
}
func (m *ImportFromS3Response) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportFromS3Response.DiscardUnknown(m)
}

var xxx_messageInfo_ImportFromS3Response proto.InternalMessageInfo

func (m *ImportFromS3Response) GetOperation() *Ydb_Operations.Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

/// Data
type YdbDumpFormat struct {
	Columns              []string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YdbDumpFormat) Reset()         { *m = YdbDumpFormat{} }
func (m *YdbDumpFormat) String() string { return proto.CompactTextString(m) }
func (*YdbDumpFormat) ProtoMessage()    {}
func (*YdbDumpFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{7}
}

func (m *YdbDumpFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YdbDumpFormat.Unmarshal(m, b)
}
func (m *YdbDumpFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YdbDumpFormat.Marshal(b, m, deterministic)
}
func (m *YdbDumpFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YdbDumpFormat.Merge(m, src)
}
func (m *YdbDumpFormat) XXX_Size() int {
	return xxx_messageInfo_YdbDumpFormat.Size(m)
}
func (m *YdbDumpFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_YdbDumpFormat.DiscardUnknown(m)
}

var xxx_messageInfo_YdbDumpFormat proto.InternalMessageInfo

func (m *YdbDumpFormat) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

type ImportDataResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportDataResult) Reset()         { *m = ImportDataResult{} }
func (m *ImportDataResult) String() string { return proto.CompactTextString(m) }
func (*ImportDataResult) ProtoMessage()    {}
func (*ImportDataResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{8}
}

func (m *ImportDataResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportDataResult.Unmarshal(m, b)
}
func (m *ImportDataResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportDataResult.Marshal(b, m, deterministic)
}
func (m *ImportDataResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportDataResult.Merge(m, src)
}
func (m *ImportDataResult) XXX_Size() int {
	return xxx_messageInfo_ImportDataResult.Size(m)
}
func (m *ImportDataResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportDataResult.DiscardUnknown(m)
}

var xxx_messageInfo_ImportDataResult proto.InternalMessageInfo

type ImportDataRequest struct {
	OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3" json:"operation_params,omitempty"`
	// Full path to table
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Data serialized in the selected format. Restrictions:
	// - sorted by primary key;
	// - all keys must be from the same partition;
	// - table has no global secondary indexes;
	// - size of serialized data is limited to 8 MB.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Types that are valid to be assigned to Format:
	//	*ImportDataRequest_YdbDump
	Format               isImportDataRequest_Format `protobuf_oneof:"format"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ImportDataRequest) Reset()         { *m = ImportDataRequest{} }
func (m *ImportDataRequest) String() string { return proto.CompactTextString(m) }
func (*ImportDataRequest) ProtoMessage()    {}
func (*ImportDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{9}
}

func (m *ImportDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportDataRequest.Unmarshal(m, b)
}
func (m *ImportDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportDataRequest.Marshal(b, m, deterministic)
}
func (m *ImportDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportDataRequest.Merge(m, src)
}
func (m *ImportDataRequest) XXX_Size() int {
	return xxx_messageInfo_ImportDataRequest.Size(m)
}
func (m *ImportDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportDataRequest proto.InternalMessageInfo

func (m *ImportDataRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if m != nil {
		return m.OperationParams
	}
	return nil
}

func (m *ImportDataRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ImportDataRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type isImportDataRequest_Format interface {
	isImportDataRequest_Format()
}

type ImportDataRequest_YdbDump struct {
	YdbDump *YdbDumpFormat `protobuf:"bytes,4,opt,name=ydb_dump,json=ydbDump,proto3,oneof"`
}

func (*ImportDataRequest_YdbDump) isImportDataRequest_Format() {}

func (m *ImportDataRequest) GetFormat() isImportDataRequest_Format {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *ImportDataRequest) GetYdbDump() *YdbDumpFormat {
	if x, ok := m.GetFormat().(*ImportDataRequest_YdbDump); ok {
		return x.YdbDump
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ImportDataRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ImportDataRequest_YdbDump)(nil),
	}
}

type ImportDataResponse struct {
	// operation.result = ImportDataResult
	Operation            *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ImportDataResponse) Reset()         { *m = ImportDataResponse{} }
func (m *ImportDataResponse) String() string { return proto.CompactTextString(m) }
func (*ImportDataResponse) ProtoMessage()    {}
func (*ImportDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e301fc7fa8cff831, []int{10}
}

func (m *ImportDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportDataResponse.Unmarshal(m, b)
}
func (m *ImportDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportDataResponse.Marshal(b, m, deterministic)
}
func (m *ImportDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportDataResponse.Merge(m, src)
}
func (m *ImportDataResponse) XXX_Size() int {
	return xxx_messageInfo_ImportDataResponse.Size(m)
}
func (m *ImportDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportDataResponse proto.InternalMessageInfo

func (m *ImportDataResponse) GetOperation() *Ydb_Operations.Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func init() {
	proto.RegisterEnum("Ydb.Import.ImportProgress_Progress", ImportProgress_Progress_name, ImportProgress_Progress_value)
	proto.RegisterEnum("Ydb.Import.ImportFromS3Settings_Scheme", ImportFromS3Settings_Scheme_name, ImportFromS3Settings_Scheme_value)
	proto.RegisterType((*ImportProgress)(nil), "Ydb.Import.ImportProgress")
	proto.RegisterType((*ImportItemProgress)(nil), "Ydb.Import.ImportItemProgress")
	proto.RegisterType((*ImportFromS3Settings)(nil), "Ydb.Import.ImportFromS3Settings")
	proto.RegisterType((*ImportFromS3Settings_Item)(nil), "Ydb.Import.ImportFromS3Settings.Item")
	proto.RegisterType((*ImportFromS3Result)(nil), "Ydb.Import.ImportFromS3Result")
	proto.RegisterType((*ImportFromS3Metadata)(nil), "Ydb.Import.ImportFromS3Metadata")
	proto.RegisterType((*ImportFromS3Request)(nil), "Ydb.Import.ImportFromS3Request")
	proto.RegisterType((*ImportFromS3Response)(nil), "Ydb.Import.ImportFromS3Response")
	proto.RegisterType((*YdbDumpFormat)(nil), "Ydb.Import.YdbDumpFormat")
	proto.RegisterType((*ImportDataResult)(nil), "Ydb.Import.ImportDataResult")
	proto.RegisterType((*ImportDataRequest)(nil), "Ydb.Import.ImportDataRequest")
	proto.RegisterType((*ImportDataResponse)(nil), "Ydb.Import.ImportDataResponse")
}

func init() { proto.RegisterFile("ydb_import.proto", fileDescriptor_e301fc7fa8cff831) }

var fileDescriptor_e301fc7fa8cff831 = []byte{
	// 945 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0x2d, 0x59, 0x96, 0x46, 0xb1, 0x4d, 0x6f, 0x5d, 0x83, 0x76, 0x7f, 0x6c, 0x30, 0x28,
	0x22, 0xeb, 0x40, 0x01, 0x0a, 0xda, 0xa2, 0x40, 0x81, 0x40, 0x3f, 0x74, 0xa2, 0xd6, 0x91, 0x84,
	0x95, 0x02, 0x34, 0x27, 0x62, 0x49, 0xae, 0x6c, 0x22, 0x22, 0x97, 0xe5, 0x2e, 0x8b, 0xe8, 0xe6,
	0x47, 0x68, 0xaf, 0x3d, 0x06, 0xe8, 0x4b, 0xf4, 0x1d, 0x0a, 0xf4, 0xd0, 0x63, 0xcf, 0x7e, 0x86,
	0x1e, 0x0b, 0xee, 0x92, 0xb4, 0x84, 0xa4, 0x70, 0x81, 0xf6, 0xb6, 0xfc, 0xe6, 0x9b, 0x9d, 0xfd,
	0xbe, 0x9d, 0x59, 0x82, 0xbe, 0xf2, 0x5d, 0x27, 0x08, 0x63, 0x96, 0x08, 0x2b, 0x4e, 0x98, 0x60,
	0x08, 0x5e, 0xf9, 0xae, 0x35, 0x92, 0xc8, 0x49, 0x77, 0xe5, 0xbb, 0x9d, 0x38, 0x75, 0x97, 0x81,
	0xd7, 0x21, 0x71, 0xd0, 0x91, 0x0c, 0xde, 0x21, 0x51, 0xc4, 0x04, 0x11, 0x01, 0x8b, 0x78, 0xe7,
	0x07, 0xb2, 0x0c, 0x7c, 0xb9, 0x56, 0xf9, 0x27, 0xe7, 0xef, 0xcf, 0xc9, 0xea, 0xb0, 0x98, 0x26,
	0xeb, 0xd4, 0xd3, 0x2b, 0xc6, 0xae, 0x96, 0x54, 0x51, 0xdc, 0x74, 0xd1, 0x11, 0x41, 0x48, 0xb9,
	0x20, 0x61, 0xac, 0x08, 0xe6, 0x6f, 0x1a, 0xec, 0xa9, 0xa3, 0x4c, 0x13, 0x76, 0x95, 0x50, 0xce,
	0xcd, 0x5f, 0x35, 0xa8, 0x17, 0x1f, 0xc8, 0x80, 0xc3, 0x29, 0x9e, 0x3c, 0xc3, 0xf6, 0x6c, 0xe6,
	0xbc, 0x1c, 0xcf, 0xa6, 0xf6, 0x60, 0x74, 0x31, 0xb2, 0x87, 0xfa, 0x03, 0x74, 0x04, 0xa8, 0x8c,
	0x4c, 0xb1, 0x3d, 0xed, 0xe1, 0xd1, 0xf8, 0x99, 0xae, 0xa1, 0x13, 0x38, 0x2a, 0xf1, 0x39, 0xee,
	0x8d, 0x67, 0x17, 0x36, 0x76, 0x86, 0xbd, 0x79, 0x4f, 0xdf, 0xda, 0x88, 0xf5, 0x5f, 0x8e, 0x2e,
	0x87, 0xce, 0x68, 0x3c, 0xb4, 0xbf, 0xb3, 0x67, 0x7a, 0x05, 0x1d, 0xc0, 0x6e, 0x19, 0x1b, 0x4e,
	0xc6, 0xb6, 0x5e, 0x45, 0xc7, 0xf0, 0x61, 0x09, 0x0d, 0x7a, 0xe3, 0x81, 0x7d, 0x79, 0xd9, 0x9b,
	0x8f, 0x26, 0x63, 0x7d, 0x7b, 0xa3, 0x7a, 0x1e, 0xb2, 0x87, 0x7a, 0xcd, 0xfc, 0x5d, 0x03, 0xa4,
	0xf4, 0x8c, 0x04, 0x0d, 0x4b, 0x19, 0xa7, 0xd0, 0x8c, 0x49, 0x22, 0xb8, 0x23, 0x98, 0x20, 0x4b,
	0x43, 0x3b, 0xd3, 0x5a, 0xbb, 0x18, 0x24, 0x34, 0xcf, 0x10, 0xf4, 0x18, 0xf6, 0x15, 0xc1, 0x63,
	0x61, 0xbc, 0xa4, 0x82, 0xfa, 0xc6, 0x96, 0x24, 0xed, 0x49, 0x78, 0x50, 0xa0, 0xe8, 0x2b, 0x00,
	0x2e, 0x48, 0x22, 0x9c, 0xcc, 0x49, 0xa3, 0x72, 0xa6, 0xb5, 0x9a, 0xdd, 0x13, 0x4b, 0xd9, 0x6c,
	0x15, 0x36, 0x5b, 0xf3, 0xc2, 0x66, 0xdc, 0x90, 0xec, 0xec, 0x1b, 0x7d, 0x0e, 0x75, 0x1a, 0xf9,
	0x2a, 0xb1, 0x7a, 0x6f, 0xe2, 0x0e, 0x8d, 0xfc, 0xec, 0xcb, 0xfc, 0xa9, 0x0a, 0x87, 0x4a, 0xd2,
	0x45, 0xc2, 0xc2, 0xd9, 0x93, 0x19, 0x15, 0x22, 0x88, 0xae, 0x38, 0x3a, 0x93, 0xfb, 0xc5, 0x2c,
	0x88, 0x84, 0x54, 0xd4, 0xe8, 0x57, 0x7f, 0xbc, 0x6d, 0x6b, 0xb8, 0x44, 0xd1, 0x53, 0xa8, 0x71,
	0xef, 0x9a, 0x86, 0x54, 0x8a, 0xd9, 0xeb, 0x3e, 0xb6, 0xee, 0x5a, 0xcf, 0x7a, 0xdf, 0x9e, 0xd6,
	0x4c, 0xd2, 0x71, 0x9e, 0x86, 0x3e, 0x86, 0x9a, 0x9b, 0x7a, 0xaf, 0xa9, 0x90, 0x4a, 0x8b, 0x02,
	0x39, 0x86, 0x1e, 0x01, 0x10, 0xcf, 0xa3, 0x9c, 0x3b, 0xaf, 0xe9, 0x4a, 0x4a, 0x2a, 0x18, 0x0d,
	0x85, 0x7f, 0x4b, 0x57, 0x19, 0x89, 0x53, 0x2f, 0xa1, 0x42, 0x92, 0xb6, 0xd7, 0x49, 0x0a, 0xcf,
	0x48, 0x03, 0xd8, 0x0e, 0x04, 0x0d, 0xb9, 0x51, 0x3b, 0xab, 0xb4, 0x9a, 0xdd, 0xcf, 0xee, 0x3d,
	0x67, 0x76, 0xbb, 0xfd, 0xda, 0xcf, 0xb7, 0xed, 0xad, 0x96, 0x86, 0x55, 0x2e, 0x3a, 0x87, 0xa6,
	0x4f, 0xb9, 0x97, 0x04, 0x71, 0x36, 0x01, 0xc6, 0x8e, 0x2c, 0xb5, 0xf3, 0xf6, 0xb6, 0x5d, 0x31,
	0x6e, 0x34, 0xbc, 0x1e, 0x43, 0x6d, 0x38, 0x88, 0xd2, 0xd0, 0xa5, 0x89, 0xc3, 0x16, 0x4e, 0x42,
	0x45, 0x12, 0x50, 0x6e, 0xd4, 0xe5, 0x85, 0xef, 0xab, 0xc0, 0x64, 0x81, 0x15, 0x7c, 0xe2, 0x42,
	0x35, 0xab, 0x86, 0xce, 0x61, 0x97, 0xb3, 0x34, 0xf1, 0xa8, 0x13, 0x27, 0x74, 0x11, 0xbc, 0xd9,
	0xf0, 0xfc, 0xa1, 0x0a, 0x4d, 0x65, 0x04, 0x75, 0x40, 0xf7, 0x29, 0x17, 0x41, 0x24, 0x67, 0xd1,
	0x89, 0x89, 0xb8, 0x96, 0x37, 0x50, 0xb0, 0xf7, 0xd7, 0xa2, 0x53, 0x22, 0xae, 0x4d, 0x0b, 0x6a,
	0xca, 0x79, 0xb4, 0x0f, 0xcd, 0xcd, 0x39, 0xab, 0x43, 0xf5, 0xf9, 0x7c, 0x3e, 0xd5, 0x35, 0xd4,
	0x80, 0xed, 0x6c, 0x35, 0xd3, 0xb7, 0xcc, 0xc3, 0xa2, 0xcb, 0x95, 0x2d, 0x98, 0xf2, 0x74, 0x29,
	0xcc, 0x3f, 0xb5, 0xcd, 0x4e, 0x79, 0x41, 0x05, 0xf1, 0x89, 0x20, 0xe8, 0x6b, 0xa8, 0xf3, 0xdc,
	0x39, 0x79, 0xea, 0x66, 0xf7, 0xec, 0x3e, 0x87, 0x71, 0x99, 0x81, 0x9e, 0x42, 0x3d, 0xce, 0x07,
	0x29, 0xef, 0xa3, 0x47, 0xef, 0x66, 0x17, 0xa3, 0x66, 0x15, 0x0b, 0x5c, 0x26, 0x21, 0x1b, 0xf6,
	0xe4, 0x0d, 0x39, 0xe5, 0x36, 0x15, 0x79, 0xcd, 0x9f, 0xbe, 0xbb, 0xcd, 0xfa, 0xd4, 0xe2, 0x5d,
	0x99, 0x55, 0x3e, 0x4c, 0xbf, 0x68, 0xf0, 0xc1, 0xa6, 0xea, 0xef, 0x53, 0xca, 0x05, 0xfa, 0x06,
	0xf4, 0xf2, 0xdd, 0x73, 0x62, 0x92, 0x90, 0xb0, 0x50, 0x79, 0x2a, 0x0b, 0x4c, 0x8a, 0x20, 0xbf,
	0x5b, 0x4e, 0x25, 0x0d, 0xef, 0xb3, 0x4d, 0x00, 0xf5, 0xd7, 0x9c, 0xda, 0xfa, 0x77, 0x4e, 0x15,
	0x53, 0x57, 0xe4, 0x99, 0x93, 0xcd, 0x5b, 0xc0, 0x94, 0xc7, 0x2c, 0xe2, 0x14, 0x7d, 0x09, 0x8d,
	0xb2, 0x5c, 0x7e, 0xc0, 0xe3, 0x7f, 0x3c, 0x20, 0xbe, 0xe3, 0x9a, 0xe7, 0xb0, 0xfb, 0xca, 0x77,
	0x87, 0x69, 0x18, 0x5f, 0xb0, 0x24, 0x24, 0x02, 0x19, 0xb0, 0xe3, 0xb1, 0x65, 0x1a, 0x46, 0x99,
	0xd0, 0x4a, 0xab, 0x81, 0x8b, 0x4f, 0x13, 0x81, 0xae, 0x6a, 0x0f, 0x89, 0x20, 0x79, 0x5b, 0xfc,
	0xa1, 0xc1, 0xc1, 0x3a, 0xf8, 0xff, 0xbb, 0x86, 0xa0, 0x7a, 0xd7, 0xe3, 0x58, 0xae, 0xd1, 0x27,
	0x50, 0xcd, 0x7a, 0x4f, 0x3e, 0x1c, 0x0f, 0xfb, 0x8d, 0xb7, 0xb7, 0xed, 0x6d, 0xe3, 0xe6, 0xe6,
	0xa6, 0x8a, 0x25, 0x8c, 0xbe, 0x80, 0x7a, 0xf6, 0xc3, 0xf2, 0xd3, 0x30, 0xce, 0x1f, 0xc3, 0xe3,
	0x75, 0xa3, 0x37, 0xf4, 0x3e, 0x7f, 0x80, 0x77, 0x56, 0x0a, 0xe8, 0xd7, 0xa1, 0xb6, 0x90, 0xa0,
	0xf9, 0xa2, 0x98, 0x81, 0x5c, 0xea, 0x7f, 0x33, 0xb9, 0xff, 0x11, 0x1c, 0x79, 0x2c, 0xb4, 0x56,
	0x24, 0xf2, 0xe9, 0x1b, 0x6b, 0xe5, 0xbb, 0x96, 0xfa, 0x69, 0x3b, 0x7f, 0x69, 0x9a, 0x5b, 0x93,
	0x0f, 0xf4, 0x93, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x19, 0x2e, 0xf5, 0x98, 0xcd, 0x07, 0x00,
	0x00,
}

// SetOperationParams implements ydb generic interface for setting
// operation parameters inside driver implementation.
func (m *ImportFromS3Request) SetOperationParams(v *Ydb_Operations.OperationParams) {
	m.OperationParams = v
}

// SetOperationParams implements ydb generic interface for setting
// operation parameters inside driver implementation.
func (m *ImportDataRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	m.OperationParams = v
}
