// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ydb_s3_internal.proto

package Ydb_S3Internal

import (
	Ydb "github.com/yandex-cloud/ydb-go-sdk/v2/api/protos/Ydb"
	Ydb_Operations "github.com/yandex-cloud/ydb-go-sdk/v2/api/protos/Ydb_Operations"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type S3ListingRequest struct {
	TableName            string                          `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	KeyPrefix            *Ydb.TypedValue                 `protobuf:"bytes,2,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	PathColumnPrefix     string                          `protobuf:"bytes,3,opt,name=path_column_prefix,json=pathColumnPrefix,proto3" json:"path_column_prefix,omitempty"`
	PathColumnDelimiter  string                          `protobuf:"bytes,4,opt,name=path_column_delimiter,json=pathColumnDelimiter,proto3" json:"path_column_delimiter,omitempty"`
	StartAfterKeySuffix  *Ydb.TypedValue                 `protobuf:"bytes,5,opt,name=start_after_key_suffix,json=startAfterKeySuffix,proto3" json:"start_after_key_suffix,omitempty"`
	MaxKeys              uint32                          `protobuf:"varint,6,opt,name=max_keys,json=maxKeys,proto3" json:"max_keys,omitempty"`
	ColumnsToReturn      []string                        `protobuf:"bytes,7,rep,name=columns_to_return,json=columnsToReturn,proto3" json:"columns_to_return,omitempty"`
	OperationParams      *Ydb_Operations.OperationParams `protobuf:"bytes,8,opt,name=operation_params,json=operationParams,proto3" json:"operation_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *S3ListingRequest) Reset()         { *m = S3ListingRequest{} }
func (m *S3ListingRequest) String() string { return proto.CompactTextString(m) }
func (*S3ListingRequest) ProtoMessage()    {}
func (*S3ListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a251a79ecaf5049, []int{0}
}

func (m *S3ListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3ListingRequest.Unmarshal(m, b)
}
func (m *S3ListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3ListingRequest.Marshal(b, m, deterministic)
}
func (m *S3ListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3ListingRequest.Merge(m, src)
}
func (m *S3ListingRequest) XXX_Size() int {
	return xxx_messageInfo_S3ListingRequest.Size(m)
}
func (m *S3ListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_S3ListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_S3ListingRequest proto.InternalMessageInfo

func (m *S3ListingRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *S3ListingRequest) GetKeyPrefix() *Ydb.TypedValue {
	if m != nil {
		return m.KeyPrefix
	}
	return nil
}

func (m *S3ListingRequest) GetPathColumnPrefix() string {
	if m != nil {
		return m.PathColumnPrefix
	}
	return ""
}

func (m *S3ListingRequest) GetPathColumnDelimiter() string {
	if m != nil {
		return m.PathColumnDelimiter
	}
	return ""
}

func (m *S3ListingRequest) GetStartAfterKeySuffix() *Ydb.TypedValue {
	if m != nil {
		return m.StartAfterKeySuffix
	}
	return nil
}

func (m *S3ListingRequest) GetMaxKeys() uint32 {
	if m != nil {
		return m.MaxKeys
	}
	return 0
}

func (m *S3ListingRequest) GetColumnsToReturn() []string {
	if m != nil {
		return m.ColumnsToReturn
	}
	return nil
}

func (m *S3ListingRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if m != nil {
		return m.OperationParams
	}
	return nil
}

type S3ListingResponse struct {
	Operation            *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *S3ListingResponse) Reset()         { *m = S3ListingResponse{} }
func (m *S3ListingResponse) String() string { return proto.CompactTextString(m) }
func (*S3ListingResponse) ProtoMessage()    {}
func (*S3ListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a251a79ecaf5049, []int{1}
}

func (m *S3ListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3ListingResponse.Unmarshal(m, b)
}
func (m *S3ListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3ListingResponse.Marshal(b, m, deterministic)
}
func (m *S3ListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3ListingResponse.Merge(m, src)
}
func (m *S3ListingResponse) XXX_Size() int {
	return xxx_messageInfo_S3ListingResponse.Size(m)
}
func (m *S3ListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_S3ListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_S3ListingResponse proto.InternalMessageInfo

func (m *S3ListingResponse) GetOperation() *Ydb_Operations.Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type S3ListingResult struct {
	CommonPrefixes       *Ydb.ResultSet `protobuf:"bytes,1,opt,name=common_prefixes,json=commonPrefixes,proto3" json:"common_prefixes,omitempty"`
	Contents             *Ydb.ResultSet `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	KeySuffixSize        uint32         `protobuf:"varint,3,opt,name=key_suffix_size,json=keySuffixSize,proto3" json:"key_suffix_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S3ListingResult) Reset()         { *m = S3ListingResult{} }
func (m *S3ListingResult) String() string { return proto.CompactTextString(m) }
func (*S3ListingResult) ProtoMessage()    {}
func (*S3ListingResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a251a79ecaf5049, []int{2}
}

func (m *S3ListingResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3ListingResult.Unmarshal(m, b)
}
func (m *S3ListingResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3ListingResult.Marshal(b, m, deterministic)
}
func (m *S3ListingResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3ListingResult.Merge(m, src)
}
func (m *S3ListingResult) XXX_Size() int {
	return xxx_messageInfo_S3ListingResult.Size(m)
}
func (m *S3ListingResult) XXX_DiscardUnknown() {
	xxx_messageInfo_S3ListingResult.DiscardUnknown(m)
}

var xxx_messageInfo_S3ListingResult proto.InternalMessageInfo

func (m *S3ListingResult) GetCommonPrefixes() *Ydb.ResultSet {
	if m != nil {
		return m.CommonPrefixes
	}
	return nil
}

func (m *S3ListingResult) GetContents() *Ydb.ResultSet {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *S3ListingResult) GetKeySuffixSize() uint32 {
	if m != nil {
		return m.KeySuffixSize
	}
	return 0
}

func init() {
	proto.RegisterType((*S3ListingRequest)(nil), "Ydb.S3Internal.S3ListingRequest")
	proto.RegisterType((*S3ListingResponse)(nil), "Ydb.S3Internal.S3ListingResponse")
	proto.RegisterType((*S3ListingResult)(nil), "Ydb.S3Internal.S3ListingResult")
}

func init() { proto.RegisterFile("ydb_s3_internal.proto", fileDescriptor_1a251a79ecaf5049) }

var fileDescriptor_1a251a79ecaf5049 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x51, 0x6f, 0xd3, 0x30,
	0x14, 0x85, 0x15, 0x06, 0x5b, 0xeb, 0xa9, 0x4d, 0xe7, 0x69, 0x28, 0xab, 0x84, 0xa8, 0x2a, 0x81,
	0xca, 0x84, 0x52, 0xd1, 0x3e, 0xec, 0x99, 0xb1, 0x17, 0xd8, 0x04, 0x95, 0x33, 0x21, 0xf1, 0x64,
	0x39, 0xc9, 0x2d, 0x58, 0x8d, 0xed, 0x60, 0x3b, 0xa8, 0xd9, 0x6f, 0x41, 0xfc, 0x4e, 0x1e, 0x51,
	0x9c, 0xa4, 0x29, 0x88, 0xbd, 0x55, 0xf7, 0x7e, 0xe7, 0xf4, 0x28, 0xe7, 0x1a, 0x9d, 0x95, 0x69,
	0x4c, 0xcd, 0x92, 0x72, 0x69, 0x41, 0x4b, 0x96, 0x85, 0xb9, 0x56, 0x56, 0xe1, 0xe1, 0x97, 0x34,
	0x0e, 0xa3, 0xe5, 0xfb, 0x66, 0x3a, 0x7e, 0x55, 0xa6, 0xf1, 0x3c, 0x2f, 0xe2, 0x8c, 0x27, 0x73,
	0x96, 0xf3, 0xb9, 0xa3, 0xcc, 0xbc, 0x12, 0xab, 0x1c, 0x34, 0xb3, 0x5c, 0xc9, 0x5a, 0x3a, 0x7e,
	0xf1, 0x30, 0xfa, 0x83, 0x65, 0x05, 0xd4, 0xd8, 0xf4, 0xe7, 0x01, 0x1a, 0x45, 0xcb, 0x5b, 0x6e,
	0x2c, 0x97, 0x5f, 0x09, 0x7c, 0x2f, 0xc0, 0x58, 0xfc, 0x0c, 0x21, 0xcb, 0xe2, 0x0c, 0xa8, 0x64,
	0x02, 0x02, 0x6f, 0xe2, 0xcd, 0xfa, 0xa4, 0xef, 0x26, 0x1f, 0x99, 0x00, 0x1c, 0x22, 0xb4, 0x81,
	0x92, 0xe6, 0x1a, 0xd6, 0x7c, 0x1b, 0x3c, 0x9a, 0x78, 0xb3, 0xe3, 0x85, 0x1f, 0x56, 0x51, 0xef,
	0xca, 0x1c, 0xd2, 0xcf, 0x95, 0x3d, 0xe9, 0x6f, 0xa0, 0x5c, 0x39, 0x02, 0xbf, 0x46, 0x38, 0x67,
	0xf6, 0x1b, 0x4d, 0x54, 0x56, 0x08, 0xd9, 0xea, 0x0e, 0x9c, 0xed, 0xa8, 0xda, 0xbc, 0x73, 0x8b,
	0x86, 0x5e, 0xa0, 0xb3, 0x7d, 0x3a, 0x85, 0x8c, 0x0b, 0x6e, 0x41, 0x07, 0x8f, 0x9d, 0xe0, 0xb4,
	0x13, 0x5c, 0xb7, 0x2b, 0x7c, 0x8d, 0x9e, 0x1a, 0xcb, 0xb4, 0xa5, 0x6c, 0x6d, 0x41, 0xd3, 0x2a,
	0x9d, 0x29, 0xd6, 0xd5, 0xbf, 0x3c, 0xf9, 0x7f, 0xba, 0x53, 0x87, 0xbf, 0xad, 0xe8, 0x1b, 0x28,
	0x23, 0xc7, 0xe2, 0x73, 0xd4, 0x13, 0x6c, 0x5b, 0xa9, 0x4d, 0x70, 0x38, 0xf1, 0x66, 0x03, 0x72,
	0x24, 0xd8, 0xf6, 0x06, 0x4a, 0x83, 0x2f, 0xd0, 0x49, 0x9d, 0xc7, 0x50, 0xab, 0xa8, 0x06, 0x5b,
	0x68, 0x19, 0x1c, 0x4d, 0x0e, 0x66, 0x7d, 0xe2, 0x37, 0x8b, 0x3b, 0x45, 0xdc, 0x18, 0x7f, 0x40,
	0xa3, 0x5d, 0x19, 0x34, 0x67, 0x9a, 0x09, 0x13, 0xf4, 0x5c, 0x8c, 0xe7, 0x2e, 0xc6, 0xa7, 0x76,
	0x69, 0xba, 0x9f, 0x2b, 0x87, 0x11, 0x5f, 0xfd, 0x3d, 0x98, 0xde, 0xa2, 0x93, 0xbd, 0x76, 0x4c,
	0xae, 0xa4, 0x01, 0x7c, 0x89, 0xfa, 0x3b, 0xce, 0xb5, 0x73, 0xbc, 0x38, 0x7f, 0xd0, 0x99, 0x74,
	0xec, 0xf4, 0x97, 0x87, 0xfc, 0x7d, 0xbb, 0x22, 0xb3, 0xf8, 0x12, 0xf9, 0x89, 0x12, 0x42, 0xb5,
	0xbd, 0x80, 0x69, 0x2c, 0x87, 0xce, 0xb2, 0xa6, 0x22, 0xb0, 0x64, 0x58, 0x63, 0xab, 0x86, 0xc2,
	0x17, 0xa8, 0x97, 0x28, 0x69, 0x41, 0x5a, 0xd3, 0xdc, 0xc0, 0xbf, 0x8a, 0xdd, 0x1e, 0xbf, 0x44,
	0x7e, 0xd7, 0x09, 0x35, 0xfc, 0x1e, 0x5c, 0xfd, 0x03, 0x32, 0xd8, 0xb4, 0x5f, 0x3f, 0xe2, 0xf7,
	0x70, 0xf5, 0x06, 0x8d, 0x13, 0x25, 0xc2, 0x92, 0xc9, 0x14, 0xb6, 0x61, 0x99, 0xc6, 0xe1, 0xde,
	0x9b, 0xb8, 0x1a, 0x75, 0x2f, 0x61, 0xe5, 0xae, 0xf9, 0xb7, 0xe7, 0xc5, 0x87, 0xee, 0x8e, 0x97,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x40, 0x90, 0x20, 0x22, 0x42, 0x03, 0x00, 0x00,
}

// SetOperationParams implements ydb generic interface for setting
// operation parameters inside driver implementation.
func (m *S3ListingRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	m.OperationParams = v
}
